'ci':
  - changed-files:
    - any-glob-to-any-file:
      - .github/**
      - codecov.yml

'docs':
  - changed-files:
    - any-glob-to-any-file:
      - packages/win32/doc/*
      - website/docs/**
      - CONTRIBUTING.md
      - README.md

'examples':
  - changed-files:
    - any-glob-to-any-file: examples/**

'p: generator':
  - changed-files:
    - any-glob-to-any-file: packages/generator/**

'p: win32':
  - changed-files:
    - any-glob-to-any-file: packages/win32/**

'website':
  - changed-files:
    - any-glob-to-any-file: website/**
