# Exclude generated files and examples from the coverage report.
ignore:
  - 'examples'
  - '**/example/'
  - '**/*.g.dart'
  - packages/win32/lib/src/com
  - packages/win32/lib/src/constants_nodoc.dart
  - packages/win32/lib/src/propertykey.dart
  - packages/win32/lib/src/variant.dart
