name: win32
description: >
  Access common Win32 APIs directly from Dart using FFI — no C required!
version: 5.5.2-wip
homepage: https://win32.pub
repository: https://github.com/halildurmus/win32
issue_tracker: https://github.com/halildurmus/win32/issues
documentation: https://win32.pub/docs
funding:
  - https://github.com/sponsors/halildurmus

topics:
  - win32
  - windows
  - ffi

environment:
  sdk: ^3.4.0

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  ffi: ^2.1.2

dev_dependencies:
  # Handle command-line arguments for example apps.
  args: ^2.5.0

  # Help ensure that the code is well-written.
  lints: ^4.0.0

  # Used for joining paths.
  path: ^1.9.0

  # Running the test suite.
  test: ^1.25.8
