name: 🚀 Feature request
description: Suggest a new feature or enhancement.
title: "feat: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using win32!

        Please provide the following details to help us understand your request.

  - type: markdown
    attributes:
      value: >
        Please be sure to search
        [current issues](https://github.com/halildurmus/win32/issues) before
        filling out the form fields.

  - type: textarea
    attributes:
      label: Use case
      description: |
        Please tell us the problem you are running into that led to you wanting
        a new feature.

        Is your feature request related to a problem? Please give a clear and
        concise description of what the problem is.

        Describe the alternative solutions you've considered. Is there a package
        on pub.dev that already solves this?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposal
      description: |
        Briefly but precisely describe what you would like win32 to be able to
        do.

        Consider attaching something showing what you are imagining:
         * images
         * videos
         * code samples

        Does this have to be provided by win32 directly, or can it be provided
        by a package on pub.dev? If so, maybe consider implementing and
        publishing such a package rather than filing an issue.
    validations:
      required: true
