name: generator
description: >
  TODO:
version: 0.0.1
publish_to: none

environment:
  # Change upper constraint to <4.0.0 when this PR is deployed to pub.dev:
  #   https://github.com/dart-lang/pub-dev/pull/6269
  sdk: '>=2.17.0 <3.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  # For formatting Dart code (APIs for performing dart format).
  dart_style: ^2.2.4

  # Foreign Function Interface extension methods
  ffi: ^2.0.1

  # Help ensure that the code is well-written.
  lints: ^2.0.1

  # Running the test suite.
  test: ^1.22.1

  # Windows metadata for automatically generating API signatures. The
  # relationship between these two packages is tightly coupled, since this
  # package includes a specific version of the Win32 metadata, so we pin the
  # dependency by version to avoid surprising conflicts.
  winmd: 2.4.7

  # Win32 itself
  win32: ^4.1.0

dependency_overrides:
  win32: ^4.1.0
