name: generator
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

# Declare that this package only works on Windows.
platforms:
  windows:

dependencies:
  # Handle command-line arguments for development tooling.
  args: ^2.3.1
  
  # For formatting Dart code (APIs for performing dart format).
  dart_style: ^2.2.3

  # Foreign Function Interface extension methods
  ffi: ^1.1.2

  # Help ensure that the code is well-written.
  lints: ^2.0.0

  # Used for joining paths, as part of our path_provider integration test.
  path: ^1.8.1

  # Running the test suite.
  test: ^1.21.1

  # Windows metadata for automatically generating API signatures. The
  # relationship between these two packages is tightly coupled, since this
  # package includes a specific version of the Win32 metadata, so we pin the
  # dependency by version to avoid surprising conflicts.
  winmd: 2.0.0

  # Win32 itself
  win32:
    path: ../..

dependency_overrides:
  win32:
    path: ../../
