name: Lock Threads

on:
  schedule:
    # Run every day at midnight.
    - cron: '0 0 * * *'

permissions:
  issues: write

concurrency:
  group: lock-threads

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          process-only: 'issues'
          # Number of days of inactivity before a closed issue is locked.
          issue-inactive-days: 14
          issue-comment: >
            This thread has been automatically locked since there has not been
            any recent activity after it was closed. If you are still
            experiencing a similar issue, please open a new bug, including a
            minimal reproduction of the issue.
