name: No Response

on:
  schedule:
    # Every day at 8am
    - cron: '0 8 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  no-response:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          # Don't automatically mark inactive issues+PRs as stale.
          days-before-stale: -1
          # Close needs-info issues and PRs after 14 days of inactivity.
          days-before-close: 14
          stale-issue-label: 'needs-info'
          close-issue-message: >
            Without additional information we're not able to resolve this issue.
            Feel free to add more info or respond to any questions above and we
            can reopen the case. Thanks for your contribution!
          stale-pr-label: 'needs-info'
          close-pr-message: >
            Without additional information we're not able to resolve this PR.
            Feel free to add more info or respond to any questions above.
            Thanks for your contribution!
