name: Prepare Release

on:
  workflow_dispatch:

jobs:
  prepare-release:
    uses: halildurmus/workflows/.github/workflows/prepare_release.yml@main
    with:
      update_changelog_args: '--include-path "packages/win32/**/*" --repository "../../"'
      working_directory: packages/win32
    secrets:
      token: ${{ secrets.PAT }}
