name: Publish

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  publish:
    name: Publish to pub.dev
    permissions:
      id-token: write # Required for authentication using OIDC.
      pull-requests: write # Required for writing the pull request note.
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@main
    with:
      working-directory: packages/win32
