name: win32

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/win32.yml'
      - 'analysis_options.yaml'
      - 'pubspec.yaml'
      - 'packages/win32/**'
    paths-ignore:
      - '**.md'
  push:
    branches: [main]
    paths:
      - '.github/workflows/win32.yml'
      - 'analysis_options.yaml'
      - 'pubspec.yaml'
      - 'packages/win32/**'
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      # We want to see the results on stable even if main fails (and vice
      # versa). This prevents one failure from stopping the entire run.
      fail-fast: false

      # Free config supports up to 20 concurrent jobs, so pick a sparse matrix
      # that tiles the space well.
      matrix:
        include:
          - os: windows-latest
            sdk: main
          - os: windows-2022
            sdk: beta
          - os: windows-2019
            sdk: stable
          - os: ubuntu-latest
            sdk: stable

    uses: halildurmus/halildurmus/.github/workflows/dart_package.yml@main
    with:
      dart_sdk: ${{ matrix.sdk }}
      run_tests: ${{ matrix.sdk != 'main' }}
      runs_on: ${{ matrix.os }}
      upload_coverage: ${{ matrix.sdk == 'main' }}
      validate_dartdoc_links: ${{ matrix.sdk == 'main' }}
      working_directory: packages/win32
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
